### ISSUE TITLE
[BUG] USE SEND() ERROR

### ISSUE THREAD

**Issue by IvanGostev** [futureecom/omnipay-tranzila#7]
When using the send() function, an error pops up from what? Occurs regardless of where to use in purchase or capture

JsonException: Syntax error in file C:\Users\ivang\OneDrive\Рабочий стол\chance\vendor\futureecom\omnipay-tranzila\src\Message\Responses\Response.php on line 27

**Comment by prwnr** [comment]
@IvanGostev please share more details regarding this problem, cause we did not face this problem in our environment. 

What was the JSON that got to the Response? please verify it, as this definitely is a JSON syntax problem, and the response comes from Tranzila in here.

**Comment by IvanGostev** [comment]
I wrote the code with curl without your repository and I was returned html and not json.

**Comment by IvanGostev** [comment]
> @IvanGostev please share more details regarding this problem, cause we did not face this problem in our environment. 
> 
> What was the JSON that got to the Response? please verify it, as this definitely is a JSON syntax problem, and the response comes from Tranzila in here. 

I wrote the code with curl without your repository and I was returned html and not json.

**Comment by prwnr** [comment]
> I wrote the code with curl without your repository and I was returned html and not json.

This package is set by default to `response_return_format: json` - so it seems like you are overwriting this parameter somewhere - see here:  https://github.com/futureecom/omnipay-tranzila/blob/33d99b00425d8b4815b9e77809e626ecaf379382/src/Message/Requests/AbstractRequest.php#L535

**Comment by IvanGostev** [comment]
> > I wrote the code with curl without your repository and I was returned html and not json.
> 
> This package is set by default to `response_return_format: json` - so it seems like you are overwriting this parameter somewhere, and it wont work with a HTML response.
> 
> See here:
> 
> https://github.com/futureecom/omnipay-tranzila/blob/33d99b00425d8b4815b9e77809e626ecaf379382/src/Message/Requests/AbstractRequest.php#L535


![image](https://github.com/futureecom/omnipay-tranzila/assets/91177733/46f8da79-5e45-442b-8f36-19b3a05607b9)

![image](https://github.com/futureecom/omnipay-tranzila/assets/91177733/a6463205-8fdc-48ea-859a-f0a1679ce848)

**Comment by IvanGostev** [comment]
> > > I wrote the code with curl without your repository and I was returned html and not json.
> > 
> > 
> > This package is set by default to `response_return_format: json` - so it seems like you are overwriting this parameter somewhere, and it wont work with a HTML response.
> > See here:
> > https://github.com/futureecom/omnipay-tranzila/blob/33d99b00425d8b4815b9e77809e626ecaf379382/src/Message/Requests/AbstractRequest.php#L535
> 
> ![image](https://private-user-images.githubusercontent.com/91177733/346172868-46f8da79-5e45-442b-8f36-19b3a05607b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTUzNDUsIm5iZiI6MTcyMDE5NTA0NSwicGF0aCI6Ii85MTE3NzczMy8zNDYxNzI4NjgtNDZmOGRhNzktNWU0NS00NDJiLThmMzYtMTliM2EwNTYwN2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE1NTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYmExMmE0YTVjZjI0ZTRlMDA1OWI5MzU2NGQxN2E4NGY4MjI1ZTAzNjI3ZGJkODVlNDhjYWNkM2M2NzEzMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ejD-pB0XDSr6po0NI3UbXHZzgwbr0L49X0hBj3Z0hDU)
> 
> ![image](https://private-user-images.githubusercontent.com/91177733/346173081-a6463205-8fdc-48ea-859a-f0a1679ce848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTUzNDUsIm5iZiI6MTcyMDE5NTA0NSwicGF0aCI6Ii85MTE3NzczMy8zNDYxNzMwODEtYTY0NjMyMDUtOGZkYy00OGVhLTg1OWEtZjBhMTY3OWNlODQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE1NTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YTVkZmYwNGVlNzBiZTIyYTU4NDUzMDU1Mjg2Zjc3OWQ5NTViZTA3ZGRhMGY5YTMzYzk1YWI0ODJiNjc3MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mHfALSHNe1se0zsc7AaJSXtrVkboO2ORyGrFuW7Yg5I)

The second photo shows that html

**Comment by IvanGostev** [comment]
> > > > I wrote the code with curl without your repository and I was returned html and not json.
> > > 
> > > 
> > > This package is set by default to `response_return_format: json` - so it seems like you are overwriting this parameter somewhere, and it wont work with a HTML response.
> > > See here:
> > > https://github.com/futureecom/omnipay-tranzila/blob/33d99b00425d8b4815b9e77809e626ecaf379382/src/Message/Requests/AbstractRequest.php#L535
> > 
> > 
> > ![image](https://private-user-images.githubusercontent.com/91177733/346172868-46f8da79-5e45-442b-8f36-19b3a05607b9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTUzNDUsIm5iZiI6MTcyMDE5NTA0NSwicGF0aCI6Ii85MTE3NzczMy8zNDYxNzI4NjgtNDZmOGRhNzktNWU0NS00NDJiLThmMzYtMTliM2EwNTYwN2I5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE1NTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUzYmExMmE0YTVjZjI0ZTRlMDA1OWI5MzU2NGQxN2E4NGY4MjI1ZTAzNjI3ZGJkODVlNDhjYWNkM2M2NzEzMDgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ejD-pB0XDSr6po0NI3UbXHZzgwbr0L49X0hBj3Z0hDU)
> > ![image](https://private-user-images.githubusercontent.com/91177733/346173081-a6463205-8fdc-48ea-859a-f0a1679ce848.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxOTUzNDUsIm5iZiI6MTcyMDE5NTA0NSwicGF0aCI6Ii85MTE3NzczMy8zNDYxNzMwODEtYTY0NjMyMDUtOGZkYy00OGVhLTg1OWEtZjBhMTY3OWNlODQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDE1NTcyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM5YTVkZmYwNGVlNzBiZTIyYTU4NDUzMDU1Mjg2Zjc3OWQ5NTViZTA3ZGRhMGY5YTMzYzk1YWI0ODJiNjc3MWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mHfALSHNe1se0zsc7AaJSXtrVkboO2ORyGrFuW7Yg5I)
> 
> The second photo shows that html

![image](https://github.com/futureecom/omnipay-tranzila/assets/91177733/7a0f85d3-7ab7-42bf-9283-1d4d6162a559)

**Comment by prwnr** [comment]
@IvanGostev - check what this shows, what params are there. 

```php
$request = $gateway-›capture(['amount' => '1', 'transaction_reference' => '22-000000', 1);
dd($request->getData());
```

also, perhaps your tranzilla configuration requires some changes to the what its supposed to return? cause we are using the same gateway in our setup and it returns JSONs always

**Comment by IvanGostev** [comment]
> @IvanGostev - check what this shows, what params are there.
> 
> ```
> $request = $gateway-›capture(['amount' => '1', 'transaction_reference' => '22-000000');
> dd($request->getData());
> ```
> 
> also, perhaps your tranzilla configuration requires some changes to the what its supposed to return? cause we are using the same gateway in our setup and it returns JSONs always

Everything is OK, it doesn't work in my country without a vpn

**Comment by prwnr** [comment]
> Everything is OK, it doesn't work in my country without a vpn

oh, interesting. thanks for the info!
